I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 215, in script
    system "[results[0]], [results[1]], [results[2]], [results[3]], [results[4]]"
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 215, in script
    system "[results[0]], [results[1]], [results[2]], [results[3]], [results[4]]"
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 1440, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 1354, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\character.py", line 1334, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
  File "C:\Users\dodre\Downloads\renpy-8.3.4-sdk\renpy\revertable.py", line 214, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
I wanna wake up with her name 1.0
Tue Jan 14 23:37:34 2025
